<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="coFrA_ModellingFramework" nsURI="http://www.example.org/coFrA_ModellingFramework"
    nsPrefix="coFrA_ModellingFramework">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ContextInformation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="Specification"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="Specification" value="self.context->notEmpty()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="history" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualitykinds" eType="#//QualityKinds"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="frequencykinds" eType="#//FrequencyKinds"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="privacykinds" eType="#//PrivacyKinds"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentkinds" upperBound="-1"
        eType="#//EnvironmentKinds"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredContextInformation" eSuperTypes="#//ContextInformation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="Specification HistoryCheck PrivacyCheck EnvironmentCheck"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="Specification" value="self.context->notEmpty()"/>
      <details key="HistoryCheck" value="self.contextthreatalgo->forAll(a|a.history=self.history)"/>
      <details key="PrivacyCheck" value="self.contextthreatalgo.threatsituation.threatriskalgo.risk.authenticationmechanism->forAll(a|a.privacykinds=self.privacykinds)"/>
      <details key="EnvironmentCheck" value="self.contextthreatalgo.threatsituation.threatriskalgo.risk.authenticationmechanism ->includesAll(self.environmentkinds)"/>
    </eAnnotations>
    <eOperations name="WhatThreat" ordered="false" upperBound="-1" eType="#//ThreatSituation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.contextthreatalgo.threatsituation->asSet() "/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="WhatRisk" ordered="false" upperBound="-1" eType="#//Risk">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.contextthreatalgo.threatsituation.threatriskalgo.risk->asSet() "/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextthreatalgo" upperBound="-1"
        eType="#//ContextThreatAlgo" eOpposite="#//ContextThreatAlgo/requiredcontextinformation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availablecontextinformation"
        eType="#//AvailableContextInformation" eOpposite="#//AvailableContextInformation/requiredcontextinformation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AvailableContextInformation" eSuperTypes="#//ContextInformation">
    <eOperations name="WhatThreatSituation" ordered="false" upperBound="-1" eType="#//ThreatSituation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.requiredcontextinformation.contextthreatalgo.threatsituation->asSet() "/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="WhatRequiredInfo" ordered="false" upperBound="-1" eType="#//RequiredContextInformation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.requiredcontextinformation->asSet() "/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredcontextinformation"
        eType="#//RequiredContextInformation" eOpposite="#//RequiredContextInformation/availablecontextinformation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextThreatAlgo">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="Specification"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="Specification" value="self.algo->notEmpty()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredcontextinformation"
        upperBound="-1" eType="#//RequiredContextInformation" eOpposite="#//RequiredContextInformation/contextthreatalgo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threatsituation" upperBound="-1"
        eType="#//ThreatSituation" eOpposite="#//ThreatSituation/contextthreatalgo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="history" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThreatSituation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="Specification"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="Specification" value="self.threat->notEmpty()"/>
    </eAnnotations>
    <eOperations name="WhatContextInformation" ordered="false" upperBound="-1" eType="#//RequiredContextInformation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.contextthreatalgo.requiredcontextinformation->asSet() "/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="WhatRisk" ordered="false" upperBound="-1" eType="#//Risk">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.threatriskalgo.risk->asSet() "/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextthreatalgo" upperBound="-1"
        eType="#//ContextThreatAlgo" eOpposite="#//ContextThreatAlgo/threatsituation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threatriskalgo" upperBound="-1"
        eType="#//ThreatRiskAlgo" eOpposite="#//ThreatRiskAlgo/threatsituation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThreatRiskAlgo">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="Specification"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="Specification" value="self.algo->notEmpty()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threatsituation" upperBound="-1"
        eType="#//ThreatSituation" eOpposite="#//ThreatSituation/threatriskalgo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="risk" upperBound="-1" eType="#//Risk"
        eOpposite="#//Risk/threatriskalgo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Risk">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="FactorCheck Specification"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="FactorCheck" value="self.authenticationmechanism->forAll(a|a.factorkinds&lt;>self.factorkinds)"/>
      <details key="Specification" value="self.fearedEvent->notEmpty()"/>
    </eAnnotations>
    <eOperations name="WhatAuthentication" ordered="false" upperBound="-1" eType="#//AuthenticationMechanism">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.authenticationmechanism->asSet() "/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threatriskalgo" upperBound="-1"
        eType="#//ThreatRiskAlgo" eOpposite="#//ThreatRiskAlgo/risk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authenticationmechanism"
        upperBound="-1" eType="#//AuthenticationMechanism" eOpposite="#//AuthenticationMechanism/risk"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fearedEvent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="factorkinds" upperBound="-1"
        eType="#//FactorKinds"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthenticationMechanism">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UsabilityCheck UsabilityCheck2 Specification"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="UsabilityCheck" value="AuthenticationMechanism.allInstances()->select(a|a.factorkinds=0)->asSet().usabilitykinds&lt;>0"/>
      <details key="UsabilityCheck2" value="AuthenticationMechanism.allInstances()->select(a|a.factorkinds=1)->asSet().usabilitykinds&lt;>1"/>
      <details key="Specification" value="self.mechanism->notEmpty()"/>
    </eAnnotations>
    <eOperations name="WhatRisk" ordered="false" upperBound="-1" eType="#//Risk">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.risk->asSet() "/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="risk" upperBound="-1" eType="#//Risk"
        eOpposite="#//Risk/authenticationmechanism"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mechanism" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentkinds" upperBound="-1"
        eType="#//EnvironmentKinds"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployabilitykinds" upperBound="-1"
        eType="#//DeployabilityKinds"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usabilitykinds" upperBound="-1"
        eType="#//UsabilityKinds"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="factorkinds" upperBound="-1"
        eType="#//FactorKinds"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualitykinds" eType="#//QualityKinds"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="privacykinds" eType="#//PrivacyKinds"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoFrA">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextinformation" eType="#//ContextInformation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextthreatalgo" eType="#//ContextThreatAlgo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threatriskalgo" eType="#//ThreatRiskAlgo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threatsituation" eType="#//ThreatSituation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="risk" eType="#//Risk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authenticationmechanism"
        eType="#//AuthenticationMechanism"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualityKinds">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FrequencyKinds">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrivacyKinds">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentKinds">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsabilityKinds"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeployabilityKinds">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FactorKinds">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
